language: node_js
node_js:
  - 11
  - 10
install: yarn install
sudo: false
jobs:
  include:
    - stage: docs-build
      script: cp auth.example.js auth.js && yarn run test && yarn run docs:parse
cache:
  directories:
    - node_modules
