language: node_js
node_js:
  - 11
  - 10
before_install: cp auth.example.js auth.js
install: yarn
sudo: false
jobs:
  include:
    - stage: docs-build
      script: bash ./deploy/travis.sh
cache:
  directories:
    - node_modules
