language: node_js
node_js:
  - 11
  - 10
before_instal: cp auth.example.js auth.js
install: yarn
sudo: false
jobs:
  include:
    - stage: docs-build
      script: yarn run test && yarn run docs:parse
cache:
  directories:
    - node_modules
