/** Declaration file generated by dts-gen */

export = infobox_parser;

declare function infobox_parser(infobox: string, options?: any): any;

declare namespace infobox_parser {
    const prototype: {
    };

}

